version: "3.7"

networks:
  web:
    name: web

services:
  ml-testing-toolkit:
    image: mojaloop/ml-testing-toolkit:v11.9.0
    container_name: hack_ml-testing-toolkit
    volumes:
      - "./docker/spec_files:/opt/mojaloop-testing-toolkit/spec_files"
      - "./docker/secrets:/opt/mojaloop-testing-toolkit/secrets"
    ports:
      - "15000:5000"
      - "5050:5050"
    environment:
      - AUTH_ENABLED=FALSE
    command: npm start
    depends_on:
      - mongo
    networks:
      - web
    extra_hosts:
      - "pisp-sim-scheme-adapter:172.17.0.1"
      - "ml-testing-toolkit:172.17.0.1"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:ttk-backend.hackathon2.moja-lab.live"
      - "traefik.basic.port:5050"
      - "traefik.basic.protocol=http"

  mongo:
    image: mongo
    ports:
      - "27018:27017"

  # Hmm this isn't reachable at ttk.hackathon2.moja-lab.live
  # I suspect is has something to do with how the ttk is running nginx...
  # and perhaps the request isn't being forwarded by traefik in 
  # a way it likes

  ml-testing-toolkit-ui:
    image: mojaloop/ml-testing-toolkit-ui:v11.8.5
    container_name: hack_ml-testing-toolkit-ui
    ports:
      - "6060:6060"
    environment:
      - API_BASE_URL=http://ttk-backend.hackathon2.moja-lab.live
      - AUTH_ENABLED=FALSE
    command: nginx -g "daemon off;"
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:ttk.hackathon2.moja-lab.live"
      - "traefik.basic.port:6060"
      - "traefik.basic.protocol=http"

  activity-report-redis:
    container_name: activity_report_redis
    image: "redis:5.0.4-alpine"
    ports:
      - "6379:6379"
    networks:
      - web
    restart: always

  svc-global-discovery:
    image: mojaloop/ml-iso-hackathon:snapshot
    container_name: hack_svc_global_disc
    env_file:
      - default.env
      - docker-compose.env
    ports:
      - "3003:3003"
    command: npm run start:gds:noconfig
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.port:3003"
      - "traefik.basic.protocol=http"

  ##
  # This is just a default landing page to test out our website.
  # please replace with something more useful as a demo
  ##
  landing-page:
    image: sroze/landing-page:latest
    container_name: landing-page
    restart: always
    ports:
      - "6061:80"
    networks:
      - web
    environment: 
      - MESSAGE=Welcome to Mojaloop's Entry to the ISO 20022 Hackathon
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:hackathon2.moja-lab.live"
      - "traefik.basic.port=80"
      - "traefik.basic.protocol=http"

  traefik:
    image: traefik:1.7
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik/traefik.toml:/traefik.toml
      - ./docker/traefik/acme.json:/acme.json

