version: "3.7"

networks:
  web:
    name: web

services:
  ml-testing-toolkit:
    image: mojaloop/ml-testing-toolkit:v11.9.0
    container_name: dl_ml-testing-toolkit
    volumes:
      - "./docker/spec_files:/opt/mojaloop-testing-toolkit/spec_files"
      - "./docker/secrets:/opt/mojaloop-testing-toolkit/secrets"
    ports:
      - "15000:5000"
      - "5050:5050"
    environment:
      - AUTH_ENABLED=FALSE
    command: npm start
    depends_on:
      - mongo
    networks:
      - web
    extra_hosts:
      - "pisp-sim-scheme-adapter:172.17.0.1"
      - "ml-testing-toolkit:172.17.0.1"

  mongo:
    image: mongo
    ports:
      - "27018:27017"

  ml-testing-toolkit-ui:
    image: mojaloop/ml-testing-toolkit-ui:v11.8.5
    container_name: dl_ml-testing-toolkit-ui
    ports:
      - "6060:6060"
    environment:
      - API_BASE_URL=http://ml-testing-toolkit:5050
      - AUTH_ENABLED=FALSE
    command: nginx -g "daemon off;"
    networks:
      - web

  activity-report-redis:
    container_name: activity-report-redis
    image: "redis:5.0.4-alpine"
    networks:
      - web
    restart: always

  ##
  # This is just a default landing page to test out our website.
  # please replace with something more useful as a demo
  ##
  landing-page:
    image: sroze/landing-page:latest
    container_name: landing-page
    restart: always
    ports:
      - "6061:80"
    networks:
      - web
      - default
    environment: 
      - MESSAGE=hello
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:hackathon.moja-lab.live"
      - "traefik.basic.port=80"
      - "traefik.basic.protocol=http"
      - "traefik.admin.frontend.rule=Host:hackathon.moja-lab.live"
      - "traefik.admin.protocol=https"
      - "traefik.admin.port=80"

  traefik:
    # image: traefik:<stable v1.7 from https://hub.docker.com/_/traefik>
    image: traefik:1.7
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
    # hmm not sure about this...
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik/traefik.toml:/traefik.toml
      - ./docker/traefik/acme.json:/acme.json

