version: "3.7"

networks:
  mojaloop-net:
    name: mojaloop-net

services:
  ml-testing-toolkit:
    image: mojaloop/ml-testing-toolkit:v11.9.0
    container_name: dl_ml-testing-toolkit
    volumes:
      - "./docker/spec_files:/opt/mojaloop-testing-toolkit/spec_files"
      - "./docker/secrets:/opt/mojaloop-testing-toolkit/secrets"
    ports:
      - "15000:5000"
      - "5050:5050"
    environment:
      - AUTH_ENABLED=FALSE
    command: npm start
    depends_on:
      - mongo
    networks:
      - mojaloop-net
    extra_hosts:
      - "pisp-sim-scheme-adapter:172.17.0.1"
      - "ml-testing-toolkit:172.17.0.1"

  mongo:
    image: mongo
    ports:
      - "27018:27017"

  ml-testing-toolkit-ui:
    image: mojaloop/ml-testing-toolkit-ui:v11.8.5
    container_name: dl_ml-testing-toolkit-ui
    ports:
      - "6060:6060"
    environment:
      - API_BASE_URL=http://ml-testing-toolkit:5050
      - AUTH_ENABLED=FALSE
    command: nginx -g "daemon off;"
    networks:
      - mojaloop-net

  activity-report-redis:
    container_name: activity-report-redis
    image: "redis:5.0.4-alpine"
    networks:
      - mojaloop-net
    restart: always
