version: "3.7"

networks:
  web:
    name: web

services:
  ml-testing-toolkit:
    image: mojaloop/ml-testing-toolkit:v11.9.0
    container_name: hack_ml-testing-toolkit
    volumes:
      - "./docker/spec_files:/opt/mojaloop-testing-toolkit/spec_files"
      - "./docker/secrets:/opt/mojaloop-testing-toolkit/secrets"
    ports:
      - "5000:5000"
      - "5050:5050"
    environment:
      - AUTH_ENABLED=FALSE
    command: npm start
    networks:
      - web
    extra_hosts:
      - "pisp-sim-scheme-adapter:172.17.0.1"
      - "ml-testing-toolkit:172.17.0.1"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:ttk-backend.hackathon2.moja-lab.live"
      - "traefik.port=5000"
      - "traefik.protocol=http"

  ## Hmm this isn't reachable at ttk.hackathon2.moja-lab.live
  ## I suspect is has something to do with how the ttk is running nginx...
  ## and perhaps the request isn't being forwarded by traefik in 
  ## a way it likes

  # ml-testing-toolkit-ui:
  #   image: mojaloop/ml-testing-toolkit-ui:v11.8.5
  #   container_name: hack_ml-testing-toolkit-ui
  #   ports:
  #     - "6060:6060"
  #   environment:
  #     - API_BASE_URL=http://ttk-backend.hackathon2.moja-lab.live
  #     - AUTH_ENABLED=FALSE
  #   command: nginx -g "daemon off;"
  #   networks:
  #     - web
  #   labels:
  #     - "traefik.docker.network=web"
  #     - "traefik.enable=true"
  #     - "traefik.frontend.rule=Host:ttk.hackathon2.moja-lab.live"
  #     - "traefik.port=6060"
  #     - "traefik.protocol=http"

  activity-report-redis:
    container_name: activity_report_redis
    image: "redis:5.0.4-alpine"
    ports:
      - "6379:6379"
    networks:
      - web
    restart: always

  svc-global-discovery:
    image: mojaloop/ml-iso-hackathon:snapshot.5
    container_name: hack_svc_global_disc
    ports:
      - "3003:3003"
    command: npm run start:gds
    depends_on: 
      - activity-report-redis
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=3003"
      - "traefik.frontend.rule=Host:gds.hackathon2.moja-lab.live"
      - "traefik.protocol=http"
    volumes:
      - ./docker-compose.env:/opt/app/default.env

  svc-moja-bank:
    image: mojaloop/ml-iso-hackathon:snapshot.5
    container_name: hack_svc_moja_bank
    command: npm run start:moja
    restart: always
    depends_on: 
      - activity-report-redis
    ports:
      - "3002:3002"
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=3002"
      - "traefik.frontend.rule=Host:mojabank.hackathon2.moja-lab.live"
      - "traefik.protocol=http"
    volumes:
      - ./docker-compose.env:/opt/app/default.env

  svc-sender-bank:
    build:
      context: ./
      dockerfile: modules/svcMojaBank/Dockerfile
    image: mojaloop/ml-iso-hackathon:snapshot.5
    command: npm run start:sender:noconfig
    restart: always
    container_name: hack_svc_sender_bank
    networks:
      - web
    ports:
      - "3103:3103"
    env_file:
      - default.env
      - docker-compose.env
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.port:3103"
      - "traefik.basic.frontend.rule=Host:senderbank.hackathon2.moja-lab.live"
      - "traefik.basic.protocol=http"
    volumes:
       - ./docker-compose.env:/opt/app/default.env

  svc-activitylog-collector:
    image: mojaloop/ml-iso-hackathon:snapshot.5
    container_name: hack_svc_activitylog_col
    env_file:
      - default.env
      - docker-compose.env
    ports:
      - "7075:7075"
    command: npm run start:actlogcol
    depends_on: 
      - activity-report-redis
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=7075"
      - "traefik.frontend.rule=Host:actlog.hackathon2.moja-lab.live"
      - "traefik.protocol=http"
    volumes:
      - ./docker-compose.env:/opt/app/default.env

  svc-simulator-ui:
    image: mojaloop/ml-iso-hackathon:snapshot.5
    container_name: hack_svc_sim_ui
    ports:
      - "7070:3000"
    command: npm run start:ui
    depends_on: 
      - svc-activitylog-collector
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:sim.hackathon2.moja-lab.live"
      - "traefik.protocol=http"
    volumes:
      - ./docker-compose.env:/opt/app/default.env

  ##
  # This is just a default landing page to test out our website.
  # please replace with something more useful as a demo
  ##
  landing-page:
    image: sroze/landing-page:latest
    container_name: landing-page
    restart: always
    ports:
      - "6061:80"
    networks:
      - web
    environment: 
      - MESSAGE=Welcome to Mojaloop's Entry to the ISO 20022 Hackathon
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:hackathon2.moja-lab.live"
      - "traefik.port=80"
      - "traefik.protocol=http"

  traefik:
    image: traefik:1.7
    container_name: traefik
    restart: always
    # Disable logging as it is far too verbose for debugging locally
    # logging:
    #   driver: none
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik/traefik.toml:/traefik.toml
      - ./docker/traefik/acme.json:/acme.json
