debug = false

logLevel = "DEBUG"
# logLevel = "ERROR"
defaultEntryPoints = ["https","http"]
#defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
#    [entryPoints.http.redirect]
#    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "hackathon2.moja-lab.live"
# domain = "hackathon.moja-lab.live"
# domain = "thingo.moja-lab.live"
watch = true
exposedByDefault = false

[acme]
email = "don+isohack@coil.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"
